linkorb/repo-ansible

- README.md
- docs/SchemaIDESupport.md
- repo.yaml
- templates/.devcontainer/devcontainer.json.j2
Documents how to enable repo.yaml file autocomplete support in VSCode/JetBrains IDEs, and automates this configuration for CodeSpaces/Devcontainer as well.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> Schema IDE autocomplete support #8278

- repo.schema.yaml
> Additional schema properties

- tasks/generate-files.yaml
- templates/.github/workflows/repo-ansible.yaml
> feat: automatic repo-ansible run workflow #8277

- .github/workflows/repo-ansible.yaml
> ci: repo-ansible workflow #8277

- repo.schema.yaml
- templates/.devcontainer/devcontainer.json.j2
- templates/.devcontainer/postCreate.sh.j2
Partial integration of changes proposed in https://github.com/linkorb/repo-ansible/pull/29
> Integrate changes from #8154

- repo.schema.yaml
Previous change would break existing workflows. Instead set it out as an opt out option.
> fix: private packagist enabled by default #8154

- repo.schema.yaml
- tasks/generate-files.yaml
- templates/.github/workflows/dependabot-auto-merge.yaml
> feat(dependabot): PR auto-merge workflow #8279

- repo.schema.yaml
> docs: note Dependabot PR automerge CI behaviour

- .github/workflows/dependabot-auto-merge.yaml
- .github/workflows/repo-ansible.yaml
- CODE_OF_CONDUCT.md
> chore: repo-ansible run

- README.md
- docs/partials/readme.usage.md
- repo.schema.yaml
- tasks/pull-request.yaml
- tasks/push.yaml
- templates/.github/settings.yml.j2
> fix: make default branch configurable #8380

- templates/.github/workflows/repo-ansible.yaml
> Repo ansible workflow fixes 8309

- .github/workflows/repo-ansible.yaml
- templates/.github/workflows/repo-ansible.yaml
Useful when debugging the repo-ansible workflow itself, or when extending functionality. It could also help potentially those that want to trigger the workflow by hand/automated fashion across batches of repositories.
> feat(workflow): allow manual workflow triggering

- .github/workflows/repo-ansible.yaml
- templates/.github/workflows/repo-ansible.yaml
> fix(workflow): smallcase env vars error #8309

- templates/.devcontainer/devcontainer.json.j2
- templates/README.md.j2
> Remove CR_PAT #8374

- templates/CODEOWNERS.j2
> fix: syntax for codeowners template file

- docs/AnsibleInstallation.md
> docs: +pip failure cases for ansible install

- templates/.github/settings.yml.j2
The template resulted in yaml that fails linting.
> fix: Remove extraneous newline

- .github/settings.yml
- CODEOWNERS
- repo.schema.yaml
- templates/.github/settings.yml.j2
> Enable archiving support #8275

- templates/.github/workflows/dependabot-auto-merge.yaml
> chore(deps): upgrade dependabot merge action #8516

- templates/.github/workflows/40-helm.yaml
- templates/.github/workflows/90-cleanup.yaml
Switch actions to their latest version to avoid the Nodejs version 16 deprecation messages in GitHub actions.
> chore(ci): update actions versions used #8541

- tasks/other-dev-generated-files.yaml
- templates/.github/workflows/00-start.yaml.j2
- templates/.github/workflows/10-review.yaml.j2
- templates/.github/workflows/30-release-and-build.yaml.j2
- templates/.github/workflows/40-helm.yaml.j2
- templates/.github/workflows/50-security.yaml.j2
- templates/.github/workflows/90-cleanup.yaml.j2
Trigger container builds and publishing on GitHub when changes are merged into the default branch.
Change required conversion of existing sdlc_workflows into jinja templated files, which also fixed a previous omission where these workflows would hold a placeholder value in the top comment.
> feat: workflows, additional release trigger #8572

- templates/.github/workflows/10-review.yaml.j2
> fix: conventional commit action version

- templates/.github/workflows/30-release-and-build.yaml.j2
> fix(ci): write-file-action no short version #0000

- templates/.github/workflows/30-release-and-build.yaml.j2
- templates/.github/workflows/90-cleanup.yaml.j2
- templates/.releaserc
> Extend conventional commits #8977

- .github/workflows/build-and-release-container.yaml
- .gitignore
When a tag is pushed, convert it to a GitHub release, as with the previous bundling operation.
> Upgrade tag to release

- .github/workflows/build-and-release-container.yaml
> fix(ci): workflow requires contents write permission

- .github/pull_request_template.md
- templates/pull_request_template.md.j2
> Update pull request template to match linkorb/.github

- CODEOWNERS
- repo.yaml
> chore: switch codeowner configuration #0000

- .github/workflows/dependabot-auto-merge.yaml
- .github/workflows/repo-ansible.yaml
- .github/workflows/update-readme.yaml
- templates/.github/workflows/dependabot-auto-merge.yaml
- templates/.github/workflows/repo-ansible.yaml
The way they have been now renamed they will be better grouped in the actions tab, and consistently named.
> style(ci): rename workflow for consistency #0000

- .github/workflows/repo-ansible.yaml
- .github/workflows/update-readme.yaml
- README.md
- docs/partials/readme.installation.md
- requirements.txt
- templates/.github/workflows/repo-ansible.yaml
- templates/codeowners.j2
> Cleanup, consistenty set changes

- .github/workflows/10-review.yaml
- README.md
- docs/partials/readme.configuration.md
- repo.schema.yaml
- tasks/generate-files.yaml
- tasks/other-dev-generated-files.yaml
> Default generation of review workflow #9037

- .github/workflows/10-review.yaml
- templates/.github/workflows/10-review.yaml.j2
> style(ci): naming/presentation of review workflow #9037

- README.md
- docs/partials/readme.installation.md
> docs: note to fetch latest container image #0000

- templates/.devcontainer/docker-compose.yml.j2
The flag became obsolete and reported as a warning when used with docker-compose.
> chore: remove docker-compose version #0000

- .github/workflows/10-review.yaml
- templates/.github/workflows/10-review.yaml.j2
Disable the strict commit conventions check for Dependabot PRs.
> feat(review): exception for Dependabot #9070

- templates/.devcontainer/postCreate.sh.j2
Extends the fix introduced in https://github.com/linkorb/repo-ansible/pull/96 to be set as global config.
> fix: devcontainer + Windows + git config (--global) #9067

- README.md
- docs/partials/readme.configuration.md
- repo.schema.yaml
- tasks/devcontainer.yaml
- templates/.devcontainer/devcontainer.json.j2
> Flag to make devcontainer configuration use root level docker-compose.yaml file #9101

- library/list_extension_workflows.py
- tasks/generate-files.yaml
- tasks/other-dev-generated-files.yaml
- templates/.github/workflows/10-review.yaml.j2
- templates/.github/workflows/30-release-and-build.yaml.j2
- templates/.github/workflows/40-helm.yaml.j2
- templates/.github/workflows/50-security.yaml.j2
- templates/.github/workflows/90-cleanup.yaml.j2
Enable a way in which by naming alone additional workflows can be executed during the repo-ansible generated workflows. These will be called (and need to be defined with `workflow_call` trigger).
Workflow 00-start.yaml is an exception, due to it being a prime candidate workflow to be removed before the `sdlc_workflows` property defaults to true.
> feat: support followup workflow hooks #9143

- templates/.github/workflows/10-review.yaml.j2
- templates/.github/workflows/30-release-and-build.yaml.j2
- templates/.github/workflows/40-helm.yaml.j2
- templates/.github/workflows/50-security.yaml.j2
- templates/.github/workflows/90-cleanup.yaml.j2
> fix: missing inherits/needs fields #9143

- templates/.github/workflows/30-release-and-build.yaml.j2
> perf(ci): if possible cache build layers #0000

- .github/workflows/build-and-release-container.yaml
> ci: caching of docker layers during build #0000

- repo.schema.yaml
- tasks/generate-files.yaml
As outlined in [Task #9188](https://team.linkorb.com/cards/9188), this PR:
1. Adds an `omit_files` list to the schema
2. Skips the generation of a ***CONTRIBUTING.md*** file.
> feat: optionally skip the contributing guide #9188

- tasks/other-dev-generated-files.yaml
Docker container runs with a newer Ansible version, for which the syntax used was incompatible. Updated the playbook to make it compatible with the released container.
> fix: ansible-core==2.18.1 compatibility #0000

- .github/workflows/build-and-release-container.yaml
- .gitignore
- README.md
- docs/partials/readme.configuration.md
- library/list_migrations.py
- playbook-all.yaml
- playbook-cwd.yaml
- repo.schema.yaml
- repo.yaml
- tasks/migrations/README.md
- tasks/migrations/migration-v0.7.0.yaml
- tasks/migrations/run-step.yaml
- tasks/migrations/update-repo-yaml-version.yaml
- tasks/version-migrations.yaml
With the increasing amount of users of repo-ansible, new features and changes leave past files around. Aside from going manually over all the repositories to manually remove those files, it's a better approach to have a migration mechanism within repo-ansible.
> feat: repo-ansible versioning & migrations #9068

- templates/README.md.j2
As outlined in https://team.linkorb.com/cards/9258, this PR :
- Add title case repository name
- Move release status up
> refactor: restructure README intro section #9258

- library/yaml_format.py
- tasks/migrations/run-step.yaml
- tasks/migrations/update-repo-yaml-version.yaml
- tasks/migrations/update-version.yaml
- tasks/version-migrations.yaml
> fix: preserve multiline strings in YAML #9235

- .github/workflows/10-review.yaml
- templates/.github/workflows/10-review.yaml.j2
> fix: support longer card reference number #9213

- templates/.devcontainer/devcontainer.json.j2
- templates/.devcontainer/postCreate.sh.j2
- templates/.devcontainer/postStart.sh.j2
> Improve devcontainer local setup #0000

- templates/.devcontainer/postCreate.sh.j2
Prevent composer install from failing on larger projects where a simple composer install invocation might use more than the default php memory configuration.
> fix(devcontainer): composer memory limit #0000

- repo.yaml
- tasks/version-migrations.yaml
> Playbook idempotency for version changes #9352

- .github/workflows/10-review.yaml
- .github/workflows/auto-merge-dependabot-prs.yaml
- .github/workflows/auto-run-repo-ansible.yaml
- repo.yaml
> chore: repo-ansible run #0000

- README.md
- docs/partials/readme.configuration.md
- group_vars/all.yaml
- repo.schema.yaml
- tasks/other-dev-generated-files.yaml
- templates/.github/workflows/30-release-and-build.yaml.j2
Support for specifying additional docker build args to use during the generated release workflow.
> feat: make docker build args extensible #8559

- tasks/other-dev-generated-files.yaml
- templates/.releaserc.cjs.j2
> feat: bump package.json version in release #9468

- .github/workflows/10-review.yaml
- templates/.devcontainer/git/linkorb_commit.template
- templates/.github/workflows/10-review.yaml.j2
> feat: drop commit message length rules #9630

- templates/.github/workflows/auto-run-repo-ansible.yaml.j2
> feat: actions write permission in workflow template #8310

- .github/settings.yml
- .github/workflows/auto-label-pull-request.yaml
- tasks/generate-files.yaml
- templates/.github/workflows/auto-label-pull-request.yaml.j2
> Enable generation of labeler 9560

- templates/.github/workflows/30-release-and-build.yaml.j2
conventional-changelog-conventionalcommits is now a required npm package dependency, probably introduced through updates of packages not pinned before.
> fix: release workflow #0000

- templates/.github/workflows/10-review.yaml.j2
- templates/.github/workflows/30-release-and-build.yaml.j2
- templates/.github/workflows/auto-run-repo-ansible.yaml.j2
> chore: update GitHub Actions workflows to `actions/checkout@v5` #0000

- templates/.devcontainer/devcontainer.json.j2
If this relates to a card, please include a link to the card here. Additionally, please terminate the PR title with `#` and the card number, such as `Fix doomsday bug #1234` -->
> chore(devcontainer): bump docker-in-docker feature to v2 #0000

- templates/.github/workflows/30-release-and-build.yaml.j2
The reported issue in the action comments is no longer applicable. Tested with the latest version of the action in a separate repository and didn't encounter the stated issues.
> chore: remove docker workaround for a specific version #0000
