templates/.github/workflows/00-start.yaml
templates/.github/workflows/10-review.yaml
templates/.github/workflows/30-release-and-build.yaml
templates/.github/workflows/40-helm.yaml
templates/.github/workflows/50-security.yaml

- Reduces overlapping triggers (pull_request/pull_request_target).
- Updates action versions.
- Remove global triggers (on any push) that would trigger all pipelines all the time. It's a high number of redundant and wasteful work.

Workflow improvement

---

templates/.github/workflows/dependabot-auto-merge.yaml

The --auto flag, according to the docs, merges a PR automatically when
the PR passes branch protection rules, or has requirements checks
enabled.
Example error message from some repositories:
```
GraphQL: Pull request Protected branch rules not configured for this
branch (enablePullRequestAutoMerge)
```

Fix dependabot merge #8279

---

repo.schema.yaml
templates/.devcontainer/devcontainer.json.j2
templates/.devcontainer/postCreate.sh.j2

Change the devcontainer generation criteria to only conditionally inject the packagist token requirement, which depends on the repo.devcontainer.private_packagist token only when the project is also a PHP type project.

fix: packagist token required for PHP apps #0000

---

templates/.github/workflows/30-release-and-build.yaml.j2

Workflow used to default to the main branch, however not all the repositories have converted to the main branch, and some still use the master branch.

fix: release workflow for default branch #000

---

.github/workflows/dependabot-auto-merge.yaml
tasks/other-dev-generated-files.yaml
templates/.github/workflows/30-release-and-build.yaml.j2
templates/.releaserc

Make the release workflow easier to test by removing hardcoded organization name, and remove it's reliance on a package.json file. Previously it would overwrite the file, just to install semantic release dependencies, which can be done instead via action parameters.

fix: do not overwrite package json during release

---

templates/.github/workflows/10-review.yaml.j2
templates/.github/workflows/30-release-and-build.yaml.j2

The default GITHUB_TOKEN secret doesn't have write permissions by
default for packages. One option is to set the token by default to have
write permission, per repository, or as with this change, mark the
additional permissions requested explicitly per workflow.

Default release workflow explicit permissions #8907

---

templates/.github/workflows/30-release-and-build.yaml.j2
templates/.releaserc

Generate a .gitrelease file as the final step of the @semantic-release action. This way the file will be available in the followup docker image build step, but not part of the committed changelog.

feat: .gitrelease file for container build 

---

tasks/php-qa.yaml
templates/.devcontainer/postCreate.sh.j2
templates/.devcontainer/postStart.sh.j2

In more recent situations, where the git hook was setup it led to ambiguous errors about paths not being correct, where it used to work before. As to avoid tripping users on this confuration, it has been disabled and tracked separately as part of the 8980 epic (relating to all things PHP QA).

fix: disable composer-unused git push check #8978

---

.github/workflows/release-package.yaml
.gitignore

The purpose of this bundling is to simplify the way other users use the repo-ansible project, without needing to go through the manual cloning of this repository, ansible and its dependencies installation.
For bulk operations and development, users are still expected to clone the repository and have ansible already installed locally.

feat: bundle playbook-cwd as an executable #9005

---

tasks/retrieve-validate-repo-data.yaml

Issue crops up when the external python command is invoked, whereas for all other cases where paths are handled by Ansible modules this should not cause an issue.

fix: handlind of directories with spaces

---

templates/.devcontainer/postCreate.sh.j2

Reported fix for an issue that shows up on Windows when running devcontainers in VSCode and the git config command is failing due to different users between the host and the git directory within the container

fix: devcontainer + Windows + git config #9067

---

repo.schema.yaml
templates/.devcontainer/devcontainer.json.j2

In order to avoid ambiguity around the purpose of the docker-compose files within repositories, those that are tailored for devcontainers should reside within the .devcontainer directory.

fix: expected location of compose file #9202

---

docker/reviewdog/entrypoint.sh

There are permission issues related to the GitHub API calls that reviewdog is supposed to make, preventing the quality checks from being reported on the PR.
Disabled part of this commit and individually tracked in #9234

fix: disable PR checks reports by reviewdog #9082

---

tasks/other-dev-generated-files.yaml
templates/.releaserc.cjs.j2

The newer JavaScript module format is not supported by the semantic-release version used through the release action.
Latest version used is the semantic-release version 22.x, and with version 23.x+ there is support for the mjs format.

fix(release): use commonjs format for config #9358

---

playbook-all.yaml
playbook-cwd.yaml
tasks/version-migrations.yaml

When repo-ansible was applied to newly setup repositories, it would fail to run because these new repositories didn't include a version field. Which was a recent addition in order to enable some form of migration across repo-ansible changes.
With this change, move the migration process before all the other tasks, and remove line that referenced the `repo` object during the migrations instead of the `repo_yaml` object

fix: version errors for new configurations #0000

---

repo.schema.yaml

The GitHub interface allows up to 350 characters for the repository description. Making repo-ansible conform to those restrictions instead of the initial 100 characters length.

feat: extend repository description length #0000

---

.github/workflows/auto-run-repo-ansible.yaml

When running repo-ansible during a GitHub Actions run, changes made to the workflow files cannot be pushed unless permitted.
In the workflows, the following snippet control permissions:
```yaml
permissions:
contents: write # allow git commits & push
pull-requests: write # allow comments on PR
```
This works for repo contents (`contents: write`), but writing to workflows require `actions: write` permission. This commit adds it to the template.
However, all repos need to manually run repo-ansible and commit and push with more permissions, either as a user with write permissions or a with a PAT with workflows read/write permissions.

fix: update auto-repo-ansible permission to allow self-updates #8310

---

docs/github-actions.md
templates/.github/settings.yml.j2
templates/.github/workflows/pr-labeler.yaml.j2

Adds a _new_ GitHub action that is triggered when a pull request is made, which can run parallel to other workflows.
1. Defines a series of labels that covers the previous set of conventional-commits noun list, but with a `Type: ` prefix, and by combining some lesser used nouns to a `Type: Misc` label.
2. These labels when updated downstream and sync'd with the actual labels, should provide first-class labels with their own colors and descriptions.
3. When a PR is made, the commits are analyzed, and based on the commit prefixes, the tags are updated. This task runs in parallel to the conventional-commits check, and is intentional because we have card ID checks, which the pr-labeler can run without.
4. This workflow also uses `permissions` to allow-list only repo contents and write access …

GitHub Actions workflow to automatically apply PR labels #9650

---

README.md
docs/partials/readme.configuration.md
repo.schema.yaml
repo.yaml
tasks/other-dev-generated-files.yaml
templates/.github/workflows/30-release-and-build.yaml.j2
templates/.releaserc.cjs.j2

This is an encompassing change that improves how our semantic-release workflow, configuration, and playbooks work:
Currently, we use `codfish/semantic-release-action@v3` GitHub Action with a set of options specified in the workflow file. However, for downstream repositories that need fine-grained configuration, this can be a bit difficult to deal with.
Currently, we build a `/.releaserc.cjs` file with quite meaningful defaults. However, in the GitHub action, it uses a custom set of options, so the `.releaserc.cjs` file does _not_ get used.
This PR fixes this by dropping the external GitHub action altogether, and using `npx semantic-release` directly within the action. It sets the repo URL, so repo forks can continue to work too.
Other than the repo URL, the rest of the configuration is …

`semantic-release` customizability improvements #9706

---

templates/.github/workflows/30-release-and-build.yaml.j2

Older versions of the GitHub cache API are deprecated and cause random, deliberate, breakages starting with the 9th of April.
While we don't use those APIs directly, the docker action we depend upons seem to do so.
Disable the cache arguments as a stop gap and prevent future breakages in CI runs.

fix(ci): drop cache arguments for docker build action #0000

---

README.md
docs/partials/readme.configuration.md
repo.schema.yaml
tasks/other-dev-generated-files.yaml
templates/.github/workflows/30-release-and-build.yaml.j2
templates/.releaserc.cjs.j2

This is an encompassing change that improves how our semantic-release workflow, configuration, and playbooks work.
Currently, we use `codfish/semantic-release-action@v3` GitHub Action with a set of options specified in the workflow file. However, for downstream repositories that need fine-grained configuration, this can be a bit difficult to deal with.
Currently, we build a `/.releaserc.cjs` file with quite meaningful defaults. However, in the GitHub action, it uses a custom set of options, so the `.releaserc.cjs` file does _not_ get used.
This PR fixes this by dropping the external GitHub action altogether, and using `npx semantic-release` directly within the action. It sets the repo URL, so repo forks can continue to work too.
Other than the repo URL, the rest of the configuration is …

feat: add support for configurable semantic-release #9706

---

.github/workflows/auto-merge-dependabot-prs.yaml
templates/.github/workflows/auto-merge-dependabot-prs.yaml.j2

Based on the article
https://boostsecurity.io/blog/weaponizing-dependabot-pwn-request-at-its-finest
While the article states that usage of actions such as dependabot/fetch-metadata to some extent prevent against this types of attacks, we add an additional check to ensure that we don't followthrough with automated merging for synchronize related events.
Automatic merging of Dependabot PRs won't happen anymore when a user instructs dependabot to rebase a PR, requiring a manual merge.

feat: harden workflows against Deputy Confusion attack vector #0000

---

templates/.devcontainer/Dockerfile.j2

`Dockerfile` ref[^1] for `ENV` recommends the `ENV KEY=VALUE` format over the current `ENV KEY VALUE` format. Current Docker version complain about it during builds.
This is a quick PR that changes the `Dockerfile` template to use this format.
[^1]: https://docs.docker.com/reference/dockerfile/#env

fix: `devcontainer/Dockerfile` - use `ENV KEY=VAL` format #0000
